#!/bin/sh

read -p "Enter desired password for editor (enter for default of 'password'): " pw
pw=${pw:-password}
echo $pw

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

IMGID=$(docker run -d -p 8787:8787 --rm \
    -v $SCRIPT_DIR/src:/home/rstudio \
    -v $SCRIPT_DIR/private:/private \
    -e PASSWORD=$pw \
    openstax/kinetic-enclave-development:v0.0.2)

docker_status=$?
if [ $docker_status -ne 0 ]; then
  echo "Failed to execute docker run command, is the Docker process running?"
  exit $docker_status
fi

echo "Login as:
  username: rstudio
  password: $pw

You may close this window, rstudio will contine to run

To stop rstudio:
docker stop $IMGID"

sleep 5
open "http://localhost:8787"
